spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: cba7eea0eac434ed6798dc71beb02fae
custom:
  paymentSecretKey: test_sk_ZORzdMaqN3wBKjyXWOB85AkYXQGw