spring:
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId:
            # 내가 받을 정보
            scope: account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            # 카카오 개발자에 등록된 redirect-uri
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
custom:
  paymentSecretKey: test_sk_ZORzdMaqN3wBKjyXWOB85AkYXQGw